apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-crud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/yakubpasha-mohd/php-apps-argocd.git"
    targetRevision: HEAD
    path: "apps/php-crud"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: php-crud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
